 const UsuarioTypes = {
    ACTUALIZAR_USUARIO : 'ACTUALIZAR_USUARIO',
    AGREGAR_USUARIO : 'AGREGAR_USUARIO',
    CONFECCIONAR_USUARIO : 'CONFECCIONAR_USUARIO',
    EDITAR_USUARIO : 'EDITAR_USUARIO',
    ELIMINAR_USUARIO : 'ELIMINAR_USUARIO',
    ERROR_USUARIO : 'ERROR_USUARIO', 
    LOADING_USUARIOS : 'LOADING_USUARIOS', 
    OBTENER_USUARIOS : 'OBTENER_USUARIOS', 
    SELECCIONA_USUARIO : 'SELECCIONA_USUARIO'
  };
  
  export default UsuarioTypes;
  